---
title: "Sim 3 mgcv"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(mgcv)

options(warn=-1)
```

## Simulation 3

```{r}
n_sim <- 100
fam_names <- c("GAULS", "GAMMALS")
mod_fams <- list(gaulss(),gammals())

for (fami in 1:length(fam_names)) {
  fam_name <- fam_names[fami]
  mod_fam <- mod_fams[[fami]]
  
  res <- matrix(nrow=n_sim,ncol = 5)
  
  pb = txtProgressBar(min = 0, max = n_sim, initial = 0)
  
  for (sim_i in 1:n_sim) {
    # Load data
    sim_dat <- read.csv(paste0('./results/data/sim3/sim_size:',n_sim,'_fam:',fam_name,'_set:',sim_i-1,'.csv'))
    sim_dat$x4 <- as.factor(sim_dat$x4)
    
    # Fit model via Wood et al. (2016)
    control.g <- gam.control(maxit=500)
    gTime <- system.time(g <- gam(list(y ~ s(x0,bs='ps',m=c(2,2)) +
                                           s(x1,bs='ps',m=c(2,2)) +
                                           s(x0,x4,bs='fs',xt=list(bs="ps"),m=c(2,1)),
                                         ~ s(x2,bs='ps',m=c(2,2)) +
                                           s(x3,bs='ps',m=c(2,2))),
                                  data=sim_dat,family = mod_fam,method='REML',control = control.g),
                         gcFirst = F)
    
    # Now compute linear predictor - true linear predictor
    pred_diff_g_mean <- g$linear.predictors[,1] - sim_dat$eta_mean
    if (fam_name == "GAMMALS"){
      pred_diff_g_scale <- (-7 + log(1 + exp(g$linear.predictors[,2]))) - sim_dat$eta_scale
    }else if (fam_name == "GAULS") {
      pred_diff_g_scale <- log(0.01 + exp(g$linear.predictors[,2])) - sim_dat$eta_scale
    }
    
    # And collect mse
    eta_mse_g_mean <- (pred_diff_g_mean %*% pred_diff_g_mean)/length(pred_diff_g_mean)
    eta_mse_g_scale <- (pred_diff_g_scale %*% pred_diff_g_scale)/length(pred_diff_g_scale)
    
    res[sim_i,1] <- eta_mse_g_mean
    res[sim_i,2] <- eta_mse_g_scale
    res[sim_i,3] <- ifelse(g$outer.info$conv == "full convergence",1,0)
    res[sim_i,4] <- g$outer.info$iter
    res[sim_i,5] <- gTime[names(gTime) == "user.self"]
    
    setTxtProgressBar(pb,sim_i)
    
  }

  close(pb)
  cat("MSE (gam):",sum(res[,1])/n_sim,",",sd(res[,1]),"\n")
  cat("Failures (gam):",n_sim - sum(res[,3]),"\n")

  # Store results
  write.table(res,file=paste0('./results/sim/mgcv_sim_3_size:',n_sim,'_fam:',fam_name,'.csv'),
                sep=',',row.names = F,col.names = c("gam_mse_mean","gam_mse_scale","gam_conv","gam_iter","gam_time"))
}  
```
